#!/usr/bin/env node
import {access, copyFile, mkdir, readFile, rm, writeFile} from 'node:fs/promises';
import {execFile} from 'node:child_process';
import {promisify} from 'node:util';
import {basename, dirname, extname, resolve} from 'node:path';
import {bundle} from '@remotion/bundler';
import {renderMedia, selectComposition} from '@remotion/renderer';

const execFileAsync=promisify(execFile);
const argv=process.argv.slice(2);const args={};for(let i=0;i<argv.length;i++)if(argv[i].startsWith('--'))args[argv[i].slice(2)]=argv[i+1]&&!argv[i+1].startsWith('--')?argv[++i]:true;
const timeline=resolve(String(args.timeline??''));const output=resolve(String(args.output??'renders/workout-edit.mp4'));const preflightOnly=Boolean(args['preflight-only']);
if(!args.timeline)throw new Error('Usage: npm run render -- --timeline <final-plan.json> [--output <video.mp4>] [--quality preview|standard|high]');
const plan=JSON.parse(await readFile(timeline,'utf8'));const allowed=new Set(['none','cut','hard_cut','motion_match','cross_dissolve','fade','dip_black','whip','glitch','push_cut','slide','wipe','zoom_blur']);
const errors=[],warnings=[],t=plan.timeline??{},finite=(v)=>Number.isFinite(v),label=(s)=>`segment ${s.segment_id??'<missing>'} at ${s.composition_start??'?'}s`;
if(plan.schema_version!=='1.0')errors.push(`unsupported schema_version ${JSON.stringify(plan.schema_version)}; renderer supports "1.0"`);
if(!['muted','preserve'].includes(plan.source_audio))errors.push('source_audio must be "muted" or "preserve"');
if(!finite(t.fps)||t.fps<=0)errors.push('timeline: fps must be positive');if(!finite(t.duration_seconds)||t.duration_seconds<=0)errors.push('timeline: duration_seconds must be positive');
if(!Number.isInteger(t.width??1080)||!Number.isInteger(t.height??1920)||(t.width??1080)<=0||(t.height??1920)<=0)errors.push('timeline: width and height must be positive integers');
for(const s of t.segments??[]){const p=label(s),points=s.time_remap?.keyframes??s.time_remap?.points??s.time_remap?.curve??[];
 if(!s.source_path)errors.push(`${p}: missing source_path`);if(!finite(s.source_start)||!finite(s.source_end)||!(s.source_end>s.source_start))errors.push(`${p}: invalid source range`);if(!finite(s.composition_start)||s.composition_start<0||!finite(s.composition_duration)||!(s.composition_duration>0))errors.push(`${p}: invalid composition range`);if(!allowed.has(s.transition_in?.type))errors.push(`${p}: unsupported transition ${s.transition_in?.type}`);if(!finite(s.playback_rate)||!(s.playback_rate>0))errors.push(`${p}: playback rate must be finite and greater than zero`);
 const td=s.transition_in?.duration_seconds;if(!finite(td)||td<0)errors.push(`${p}: invalid transition duration`);else if(s.transition_in?.model==='overlap'&&td>=s.composition_duration)errors.push(`${p}: transition (${td}s) must be shorter than its ${s.composition_duration}s clip`);
 if(s.time_remap&&(!['dramatic_bell_curve','dramatic_slow_center','smooth','speed_curve',undefined].includes(s.time_remap.type)||points.length<2||points.some(x=>!finite(x.position)||x.position<0||x.position>1||!finite(x.rate??x.speed)||!((x.rate??x.speed)>0))||points.some((x,i)=>i&&x.position<=points[i-1].position)))errors.push(`${p}: invalid/non-monotonic time-remap contract`);
 const c=s.crop??s.reframe;if(c&&(!['cover','contain','fill',undefined].includes(c.fit)||[c.x,c.y].some(v=>v!==undefined&&(!finite(v)||v<0||v>100))||(c.scale!==undefined&&(!finite(c.scale)||c.scale<=0))))errors.push(`${p}: invalid crop/reframe`);
}
const soundtrack=plan.soundtrack;if(soundtrack){for(const k of ['offset_seconds','trim_start_seconds','trim_end_seconds','volume','fade_in_seconds','fade_out_seconds'])if(!finite(soundtrack[k]))errors.push(`soundtrack: ${k} must be finite`);if(soundtrack.offset_seconds<0||soundtrack.trim_start_seconds<0||soundtrack.trim_end_seconds<=soundtrack.trim_start_seconds||soundtrack.volume<0||soundtrack.fade_in_seconds<0||soundtrack.fade_out_seconds<0)errors.push('soundtrack: invalid offset, trim, volume, or fade range');if(soundtrack.fade_in_seconds+soundtrack.fade_out_seconds>t.duration_seconds-soundtrack.offset_seconds)errors.push('soundtrack: fade windows exceed audible sequence');}
const media=[...(t.segments??[]).map(s=>({path:s.source_path,end:s.source_end,owner:label(s)})),...(soundtrack?[{path:soundtrack.src,end:soundtrack.trim_end_seconds,owner:'soundtrack'}]:[])];
const protectedPaths=new Set([timeline,...media.map(m=>resolve(dirname(timeline),m.path))]);if(protectedPaths.has(output))errors.push('output path must not overwrite the timeline, a source video, or soundtrack');if(extname(output).toLowerCase()!=='.mp4')errors.push('output must use the broadly compatible .mp4 container');
for(const m of media){const path=resolve(dirname(timeline),m.path);try{await access(path);const {stdout}=await execFileAsync('ffprobe',['-v','error','-show_entries','format=duration','-of','json',path]);const duration=Number(JSON.parse(stdout).format?.duration);if(!finite(duration))errors.push(`${m.owner}: unreadable/corrupt media ${m.path}`);else if(m.end>duration+1/Math.max(1,t.fps??30))errors.push(`${m.owner}: asks for ${m.end.toFixed(3)}s but ${m.path} is ${duration.toFixed(3)}s long`);}catch(e){errors.push(`${m.owner}: missing or unreadable media ${m.path} (${e.code==='ENOENT'?'ffprobe/file unavailable':e.message.split('\n')[0]})`);}}
if(errors.length)throw new Error(`Preflight failed:\n- ${errors.join('\n- ')}`);if(preflightOnly){console.log(`Preflight OK: ${media.length} media references${warnings.length?`; warnings: ${warnings.join('; ')}`:''}`);process.exit(0)}
const publicDir=resolve('workout-remotion-editor/public/media');await rm(publicDir,{recursive:true,force:true});await mkdir(publicDir,{recursive:true});const names=new Map();for(const m of media){const src=resolve(dirname(timeline),m.path),name=basename(m.path),previous=names.get(name);if(previous&&previous!==src)throw new Error(`Preflight failed: media basename collision: ${name}`);if(!previous){names.set(name,src);await copyFile(src,resolve(publicDir,name));}}
await mkdir(dirname(output),{recursive:true});const started=Date.now();const quality=String(args.quality??'standard'),crf={preview:28,standard:20,high:16}[quality];if(crf===undefined)throw new Error(`Unknown quality preset: ${quality}`);
try{const serveUrl=await bundle({entryPoint:resolve('workout-remotion-editor/remotion/index.ts'),publicDir:resolve('workout-remotion-editor/public')});const composition=await selectComposition({serveUrl,id:'WorkoutEdit',inputProps:{plan}});await renderMedia({serveUrl,composition,codec:'h264',outputLocation:output,inputProps:{plan},pixelFormat:'yuv420p',crf,concurrency:Number(args.concurrency??2)});}catch(e){throw new Error(`Render stage failed for ${basename(timeline)} -> ${output}: ${e.message}`,{cause:e});}finally{await rm(publicDir,{recursive:true,force:true});}
const {stdout}=await execFileAsync('ffprobe',['-v','error','-show_entries','format=duration,size:stream=codec_type,codec_name,width,height,pix_fmt,r_frame_rate,sample_rate,nb_frames','-of','json',output]);const probe=JSON.parse(stdout),video=probe.streams.find(s=>s.codec_type==='video'),audio=probe.streams.find(s=>s.codec_type==='audio'),actual=Number(probe.format.duration),planned=t.duration_seconds,delta=actual-planned,tolerance=1/t.fps+.01;if(Math.abs(delta)>tolerance)throw new Error(`Validation failed: planned ${planned}s, encoded ${actual}s (delta ${delta}s exceeds ${tolerance}s)`);
const report={output,duration_seconds:actual,planned_duration_seconds:planned,duration_delta_seconds:delta,resolution:`${video.width}x${video.height}`,fps:video.r_frame_rate,video_codec:video.codec_name,pixel_format:video.pix_fmt,audio_codec:audio?.codec_name??null,audio_sample_rate:audio?.sample_rate??null,segments:t.segments.length,transitions:t.segments.filter(s=>!['none','cut','hard_cut'].includes(s.transition_in.type)).length,counter_events:t.segments.reduce((n,s)=>n+(s.counter_events?.length??0),0),soundtrack:Boolean(soundtrack),source_audio:plan.source_audio,render_seconds:(Date.now()-started)/1000,render_factor:(Date.now()-started)/1000/actual,size_bytes:Number(probe.format.size),warnings};await writeFile(`${output}.qa.json`,JSON.stringify(report,null,2)+'\n');
console.log(`Output: ${output}\nDuration: ${actual.toFixed(2)}s (delta ${delta.toFixed(3)}s)\nResolution: ${video.width}x${video.height}\nFPS: ${video.r_frame_rate}\nVideo: ${video.codec_name}\nAudio: ${audio?.codec_name??'none'}\nSegments: ${report.segments}\nTransitions: ${report.transitions}\nCounter events: ${report.counter_events}\nSoundtrack: ${soundtrack?'yes':'no'}\nSource audio: ${plan.source_audio}`);
